# Kinetic parameters

We use features of the data to obtain estimates of the following
- Bias of progenitor population to differentiation
- Average cell division rate of dividing cells
- Average cell delamination rate for delaminating cells
- Average shed rate for suprabasal cells
- Fraction of proliferating cells


We note the biases and assumptions of these calculations in the Supplemental Note.

In [9]:
# Setting up experimental data 

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sys
sys.path.append("../../analysis/")
sys.path.append("../../sim/")
import clones

plt.rcParams['figure.figsize'] = (8, 5)


import pickle

def save_object(obj, filename):
    with open(filename, 'wb') as outp:  # Overwrites any existing file.
        pickle.dump(obj, outp, pickle.HIGHEST_PROTOCOL)

def load_object(filename):
    with open(filename, 'rb') as outp:  # Overwrites any existing file.
        return pickle.load(outp)
    
def Sclones(livesize):
    nclones = livesize.shape[0]
    max_tot = np.max(np.sum(livesize,2),1)
    
    Slike = (max_tot >= 3)
    return livesize[Slike,:,:]
    
def Tclones(livesize):
    nclones = livesize.shape[0]
    max_tot = np.max(np.sum(livesize,2),1)
    
    Tlike = (max_tot == 2)
    return livesize[Tlike,:,:]

def Dclones(livesize):
    nclones = livesize.shape[0]
    max_tot = np.max(np.sum(livesize,2),1)
    
    Dlike = (max_tot == 1)
    return livesize[Dlike,:,:]


# Functions for curve-fitting and extraction of parameters

import statsmodels.api as sm
from scipy.optimize import curve_fit


def wls_fit(x, y, se):
    # Prepare the data for statsmodels (add constant term for intercept)
    X = sm.add_constant(x)

    # Perform the weighted fit
    model = sm.WLS(y, X, weights=1/se**2)
    results = model.fit()

    # Extract fitted parameters
    m, c = results.params[1], results.params[0]
    x = np.linspace(0, x[-1], 100)
    dm = results.bse[1] 
    dc = results.bse[0]

    return m, c, dm, dc

def Aexp_fn(t, μ, A):
    return A*np.exp(μ*t)

def get_mu(clone_anal):
    clone_anal = clone_anal.Dlike()
    if clone_anal.nsur[1] > 0:
        se = clone_anal.se_lcd
        se[se <= 0] = 1/np.sqrt(clone_anal.nclones)/2
        popt, pcov = curve_fit(D_exp_fn, clone_anal.tvals, clone_anal.lcd, sigma = se, 
                    absolute_sigma = True, bounds = (0,5))
        
        μ_fit = popt[0]
        μ_err = np.sqrt(np.diag(pcov))[0]
    
        return μ_fit, μ_err
    else:
        return np.nan, np.nan
    
def D_exp_fn(t, μ):
    return np.exp(-μ*(t - 7.0))*(t >= 7)  + (t < 7)


def bias_to_division(clone_anal, nboots = 1000, tlower = 3):
    ''' 
        Estimation of bias to division for proliferative cells in data
    '''

    Δλ, c, dm, dc = wls_fit(clone_anal.tvals[tlower:], np.log(clone_anal.lcd[tlower:]), clone_anal.se_lcd[tlower:])
    '''
    Δλ, se_Δλ  = curve_fit(Aexp_fn, clone_anal.tvals[tlower:], clone_anal.lcd[tlower:], sigma = clone_anal.se_lcd[tlower:], 
                        absolute_sigma = True, bounds = ((-1,0), (1, 5)))
    '''

    lcd_boots = clone_anal.boot('lcd', nboots, calc = None)
    boot_Δλ = np.zeros(nboots)
    for b in range(nboots):
        boot_Δλ[b], c, dm, dc = wls_fit(clone_anal.tvals[tlower:], np.log(lcd_boots[b,tlower:]), clone_anal.se_lcd[tlower:])

    return Δλ, np.std(boot_Δλ)




exp_folder = '../../experiment/homeo/'

colm = {'M30': 'r', 'M1': 'b', 'M14': 'g', 'M3': 'tab:orange', 'M1bis': 'tab:purple',
        'F3':  'r', 'F4': 'b', 'F11': 'g', 'F9': 'tab:orange', 'F10': 'tab:purple'}
fmice = ['F3', 'F4', 'F11', 'F9', 'F10']
mmice = ['M30', 'M1', 'M14', 'M3', 'M1bis']
sex = ['F', 'M']

In [10]:
mid = 'M'
exp_folder = '../../experiment/homeo/'

exp_data = load_object(exp_folder + 'data_ctr_' + mid + '.pkl')

livesize = exp_data['livesize']

clone_anal_M = clones.xanalysis(livesize, verbose = False, tvals = exp_data['ctrTimeClonesize'], subpop = 'S2like')

mid = 'F'
exp_folder = '../../experiment/homeo/'

exp_data = load_object(exp_folder + 'data_ctr_' + mid + '.pkl')

livesize = exp_data['livesize']

clone_anal_F = clones.xanalysis(livesize, verbose = False, tvals = exp_data['ctrTimeClonesize'], subpop = 'S2like')

In [14]:



castrated = ['M24_castre', 'M25_castre', 'M26_castre']

sex = ['castre', 'M', 'F', 'Ovx', 'Notch1_F', 'Notch1_M', 'Lgr6_F', 'Lgr6_M']


mdata = pd.DataFrame()

inv_wam_with_se = lambda v, se: np.array([np.average(1/v, weights=v**4/(se**2)), np.sqrt(np.sum(se**2/v**4))/len(v)])
wam_with_se = lambda v, se: np.array([np.average(v, weights=1/(se**2)), np.sqrt(np.sum(se**2))/len(v)])


for mid in mmice + fmice + castrated + sex:
    exp_folder = '../../experiment/homeo/'
    if 'castre' in mid:
        exp_folder = '../../experiment/castre/'
        exp_data = load_object(exp_folder + 'data_'     + mid + '.pkl')
    elif mid in ['Ovx']:
        exp_folder = '../../experiment/ovx/'
        exp_data = load_object(exp_folder + 'data_' + mid + '.pkl')
    elif mid in ['Notch1_F', 'Notch1_M']:
         exp_folder = '../../experiment/notch/'
         exp_data = load_object(exp_folder + 'data_' + mid + '.pkl')
    elif mid in ['Lgr6_F', 'Lgr6_M']:
         exp_folder = '../../experiment/lgr6/'
         exp_data = load_object(exp_folder + 'data_' + mid + '.pkl')         
    else:
        exp_data = load_object(exp_folder + 'data_ctr_' + mid + '.pkl')

    livesize = exp_data['livesize']

    clone_anal = clones.xanalysis(livesize, verbose = False, tvals = exp_data['ctrTimeClonesize'], subpop = 'S2like')


    Δλ, se_Δλ = bias_to_division(clone_anal)

    lambda_av = (clone_anal.av_tot_cs[0] - 1)/(7-2)
    lambda_se = clone_anal.se_tot_cs[0]/(7-2) + 0.5*lambda_av/5

    lcd1 = 1/clone_anal.lcd[0]
    sel1 = clone_anal.se_lcd[0]/clone_anal.lcd[0]**2

    ns2 = clone_anal.nclones

    se = clone_anal.se_lcd[3:-1]
    av = clone_anal.lcd[3:-1]
    fS = inv_wam_with_se(av, se)

    av = clone_anal.rel_sup_bas[3:-1]
    se = clone_anal.boot('rel_sup_bas', 500)[3:-1]
    nsb_b = wam_with_se(av, se)

    t0 = 3
    av = clone_anal.av_bas_cs[t0:]
    se = clone_anal.se_bas_cs[t0:]
    t = clone_anal.tvals[t0:]
    avb = wls_fit(t, av, se)

    t0 = 3
    av = clone_anal.av_bas_cs[:t0]
    se = clone_anal.se_bas_cs[:t0]
    t = clone_anal.tvals[:t0]
    bearly = wls_fit(t, av, se)



    clone_anal_D = clones.xanalysis(livesize, verbose = False, tvals = exp_data['ctrTimeClonesize'], subpop = 'Dlike')
    nd = clone_anal_D.nclones
    μ_fit, μ_err = get_mu(clone_anal_D)

    clone_anal_T = clones.xanalysis(livesize, verbose = False, tvals = exp_data['ctrTimeClonesize'], subpop = 'Tlike')
    nT = clone_anal_T.nclones

    clone_anal_T3 = clones.xanalysis(livesize, verbose = False, tvals = exp_data['ctrTimeClonesize'], subpop = 'T3like')
    nT3 = clone_anal_T3.nclones


    nclones = ns2 + nd

    ns3 = ns2 - nT
    ns4 = ns2 - nT - nT3


    clone_anal_S3p = clones.xanalysis(livesize, verbose = False, tvals = exp_data['ctrTimeClonesize'], subpop = 'Slike')

    se = clone_anal_S3p.se_lcd[3:-1]
    av = clone_anal_S3p.lcd[3:-1]
    fS3p = inv_wam_with_se(av, se)

    clone_anal_S4p = clones.xanalysis(livesize, verbose = False, tvals = exp_data['ctrTimeClonesize'], subpop = 'S4like')

    se = clone_anal_S4p.se_lcd[3:-1]
    av = clone_anal_S4p.lcd[3:-1]
    fS4p = inv_wam_with_se(av, se)  
    boot_lcd = clone_anal_S4p.boot('lcd', nboots = 1000, calc = None)
    avs = np.zeros(boot_lcd.shape[0])
    for i in range(1000):
        av = boot_lcd[i,3:-1]
        se = clone_anal_S4p.se_lcd[3:-1]
        fb = inv_wam_with_se(av, se)  
        avs[i]  = fb[0]
    fS4p[1] = np.std(avs)

    lambdaT3_av = (clone_anal_T3.av_tot_cs[0] - 1)/7
    lambdaT3_se = clone_anal_T3.se_tot_cs[0]/7

    lambda4_av = (clone_anal_S4p.av_tot_cs[0] - 1)/7
    lambda4_se = clone_anal_S4p.se_tot_cs[0]/7  

    lambdaT_av = (clone_anal_T.av_tot_cs[0] - 1)/7
    lambdaT_se = clone_anal_T.se_tot_cs[0]/7      

    mdata = pd.concat([mdata, pd.DataFrame([{
        'Mouse': mid,
        'Δ': (Δλ/lambda_av, se_Δλ/lambda_av),
        'fs': (fS[0], fS[1]),      
        'sb_rat': (nsb_b[0], nsb_b[1]),
        'λ': (lambda_av,   lambda_se),
        'fs3+': (fS3p[0], fS3p[1]),        
        'fs4+': (fS4p[0], fS4p[1]),    
        'lab2': (lcd1, sel1),     
        'rλ/f': (avb[0], avb[2]),
        'C0': (avb[1], avb[3]),
        'λT': (lambdaT_av, lambdaT_se),          
        'λT3': (lambdaT3_av, lambdaT3_se),          
        'λ4': (lambda4_av, lambda4_se),                
        'μ': (μ_fit, μ_err),
        'bearly': (bearly[0], bearly[2]),
        '#S2+': (ns2/nclones, np.sqrt((ns2/nclones)*(1 - ns2/nclones)/nclones)),
        '#S3+': (ns3/nclones, np.sqrt((ns3/nclones)*(1 - ns3/nclones)/nclones)),
        '#S4+': (ns4/nclones, np.sqrt((ns4/nclones)*(1 - ns4/nclones)/nclones)),
        '#D': (nd/nclones, np.sqrt((nd/nclones)*(1 - nd/nclones)/nclones)),
        '#T': (nT/nclones, np.sqrt((nT/nclones)*(1 - nT/nclones)/nclones)),
        '#T3': (nT3/nclones, np.sqrt((nT3/nclones)*(1 - nT3/nclones)/nclones)),
        'nclones': nclones
        }])], ignore_index=True)

# Calculate r:inf and its standard error
rinf = mdata['rλ/f'].apply(lambda x: x[0]) * mdata['fs'].apply(lambda x: x[0]) / mdata['λ'].apply(lambda x: x[0])
r_se = rinf * np.sqrt(
    (mdata['rλ/f'].apply(lambda x: x[1]/x[0]))**2 + 
    (mdata['fs'].apply(lambda x: x[1]/x[0]))**2 + 
    (mdata['λ'].apply(lambda x: x[1]/x[0]))**2
)
mdata['rinf'] = list(zip(rinf, r_se))

# Calculate μ:inf and its standard error
μinf = mdata['λ'].apply(lambda x: x[0]) * mdata['fs'].apply(lambda x: x[0]) / (1 - mdata['fs'].apply(lambda x: x[0]))
μinf_se = μinf * np.sqrt(
    (mdata['λ'].apply(lambda x: x[1]/x[0]))**2 + 
    (mdata['fs'].apply(lambda x: x[1]/x[0]))**2
)
mdata['μinf'] = list(zip(μinf, μinf_se))

μinf2 = mdata['λ'].apply(lambda x: x[0]) * (2*mdata['fs4+'].apply(lambda x: x[0])) / (1 - 2*mdata['fs4+'].apply(lambda x: x[0]))
μinf2_se = μinf * np.sqrt(
    (mdata['λ'].apply(lambda x: x[1]/x[0]))**2 + 
    (mdata['fs'].apply(lambda x: x[1]/x[0]))**2
)
mdata['μinf2'] = list(zip(μinf2, μinf2_se))

pd.set_option('display.max_columns', 500)
mdata

/home/joelh/Documents/Science/Projects/GlassyTissue/papers/StemTA_Homeostasis/squasim-homeostasis/notebooks/2_SD_model/../../analysis/clones.py:572: RuntimeWarning: invalid value encountered in divide
  self._av_tot_cs = np.sum(self.tot_ls*bas_mask*(self.tot_ls >= 0),0)/self.nsur
/tmp/ipykernel_214745/2721654887.py:104: RuntimeWarning: divide by zero encountered in log
  boot_Δλ[b], c, dm, dc = wls_fit(clone_anal.tvals[tlower:], np.log(lcd_boots[b,tlower:]), clone_anal.se_lcd[tlower:])
/home/joelh/miniforge3/envs/tisspy/lib/python3.12/site-packages/numpy/_core/_methods.py:185: RuntimeWarning: invalid value encountered in subtract
  x = asanyarray(arr - arrmean)
/home/joelh/Documents/Science/Projects/GlassyTissue/papers/StemTA_Homeostasis/squasim-homeostasis/notebooks/2_SD_model/../../analysis/clones.py:1873: RuntimeWarning: divide by zero encountered in divide
  x = (self.av_full_tot_cs - self.lcd)/self.lcd
/home/joelh/Documents/Science/Projects/GlassyTissue/papers/StemTA_Homeostasis/squasim-homeostasis/notebooks/2_SD_model/../../analysis/clones.py:640: RuntimeWarning: invalid value encountered in divide
  self._se_tot_cs = np.sqrt(np.sum(bas_mask*(self.tot_ls - self.av_tot_cs[None,:])**2,0))/self.nsur
/home/joelh/Documents/Science/Projects/GlassyTissue/papers/StemTA_Homeostasis/squasim-homeostasis/notebooks/2_SD_model/../../analysis/clones.py:572: RuntimeWarning: invalid value encountered in divide
  self._av_tot_cs = np.sum(self.tot_ls*bas_mask*(self.tot_ls >= 0),0)/self.nsur
/home/joelh/miniforge3/envs/tisspy/lib/python3.12/site-packages/statsmodels/regression/linear_model.py:1717: RuntimeWarning: divide by zero encountered in scalar divide
  return np.dot(wresid, wresid) / self.df_resid
/home/joelh/miniforge3/envs/tisspy/lib/python3.12/site-packages/statsmodels/regression/linear_model.py:1717: RuntimeWarning: invalid value encountered in scalar divide
  return np.dot(wresid, wresid) / self.df_resid
/home/joelh/Documents/Science/Projects/GlassyTissue/papers/StemTA_Homeostasis/squasim-homeostasis/notebooks/2_SD_model/../../analysis/clones.py:572: RuntimeWarning: invalid value encountered in divide
  self._av_tot_cs = np.sum(self.tot_ls*bas_mask*(self.tot_ls >= 0),0)/self.nsur

,Mouse,Δ,fs,sb_rat,λ,fs3+,fs4+,lab2,rλ/f,C0,λT,λT3,λ4,μ,bearly,#S2+,#S3+,#S4+,#D,#T,#T3,nclones,rinf,μinf,μinf2
0,M30,"(0.07784141967239673, 0.0241907403412467)","(0.562432679156235, 0.136259706375182)","(0.36424033509132214, 0.0708132493206378)","(0.14166666666666666, 0.027287808074785543)","(0.34466430514966384, 0.07261616650386256)","(0.2437193012309437, 0.05290475538698937)","(0.6, 0.02449489742783177)","(0.09223202061451374, 0.0334861537122279)","(0.830022499721002, 1.4936654699318934)","(0.11111111111111109, 0.013998684185526933)","(0.1142857142857143, 0.018070158058105024)","(0.08571428571428573, 0.015649215928719037)","(nan, nan)","(0.08096433158944027, 0.0004933245389940274)","(0.8421052631578947, 0.04829804923590775)","(0.5263157894736842, 0.06613482762500456)","(0.3508771929824561, 0.06321258874556504)","(0.15789473684210525, 0.04829804923590773)","(0.3157894736842105, 0.06156817388058966)","(0.17543859649122806, 0.0503775039171214)",57,"(0.36617154676386393, 0.17469571805407266)","(0.18209303822511902, 0.056359607038922205)","(0.13472298606002497, 0.056359607038922205)"
1,M1,"(-0.04286064434783323, 0.05312034765726469)","(0.6835980370496565, 0.13577397264659333)","(0.3410740620866465, 0.05034627019278174)","(0.12653061224489798, 0.029672909060438974)","(0.47767888036261735, 0.09149367195391744)","(0.306622291580093, 0.089546892016488)","(0.6363636363636364, 0.035063146174539574)","(0.01104348324281542, 0.017326827027284726)","(5.622735973325989, 0.8459987149125234)","(0.08163265306122448, 0.01889428775046023)","(0.10714285714285714, 0.017857142857142856)","(0.08695652173913045, 0.02104321872943901)","(0.2602192554936134, 0.07528411588530234)","(0.1295477036693462, 0.03334137266202609)","(0.7313432835820896, 0.05415294608121959)","(0.5223880597014925, 0.06102345704883558)","(0.34328358208955223, 0.058006685713137024)","(0.26865671641791045, 0.05415294608121959)","(0.208955223880597, 0.049669495472589524)","(0.1791044776119403, 0.04684462467949339)",67,"(0.05966384998096619, 0.09538927105603337)","(0.27337402508744324, 0.08401274540062613)","(0.20062863811229698, 0.08401274540062613)"
2,M14,"(-0.05697303439564331, nan)","(0.8761096629053693, 0.14187035068217632)","(0.4956842179714519, 0.05190248095861581)","(0.13442622950819674, 0.025463666468061665)","(0.62259167977305, 0.0947372989247511)","(0.40896893271529866, 0.04891982532143268)","(0.61, 0.02287749986340289)","(0.013286423794631937, 0.011382564779039251)","(2.7086608464779327, 0.5657199587528173)","(0.10084033613445377, 0.015787167002146628)","(0.08928571428571429, 0.017290104224140256)","(0.09693877551020409, 0.012608486801753782)","(nan, nan)","(0.08436011332466684, 0.01950059382617882)","(0.7093023255813954, 0.04896516755606224)","(0.5116279069767442, 0.05390180475247302)","(0.32558139534883723, 0.05052953894914609)","(0.29069767441860467, 0.04896516755606225)","(0.19767441860465115, 0.042943884806284104)","(0.18604651162790697, 0.04196249808820081)",86,"(0.08659295373023226, 0.07725963470731217)","(0.9506158541655158, 0.23689949893378098)","(0.6039273541522927, 0.23689949893378098)"
3,M3,"(-0.02263490079919701, 0.020130073468063805)","(0.5175393433680036, 0.04649848419769502)","(0.37855042300726516, 0.03158349885345801)","(0.13999999999999999, 0.02837590576856521)","(0.3610402931939561, 0.028279277191040612)","(0.32713622922170926, 0.03574659649213963)","(0.5882352941176471, 0.02487180928817511)","(0.02695680547309157, 0.007908793461862294)","(2.365719495388289, 0.4031333950661771)","(0.10084033613445377, 0.015787167002146628)","(0.14285714285714285, 0.0)","(0.09523809523809525, 0.014028236011081873)","(nan, nan)","(0.11083444346804959, 0.005313311336441095)","(0.7894736842105263, 0.046764385086244135)","(0.5657894736842105, 0.05685528086757625)","(0.5131578947368421, 0.057334070632943414)","(0.21052631578947367, 0.046764385086244135)","(0.2236842105263158, 0.04780024010173328)","(0.05263157894736842, 0.025613908599594084)",76,"(0.09965148145602012, 0.03664542987850219)","(0.15017910180971902, 0.03329555908175386)","(0.2649431508108176, 0.03329555908175386)"
4,M1bis,"(0.02022416972510424, 0.012938046621379217)","(0.4239048794676161, 0.029145886598924132)","(0.463349179017276, 0.02791630508349488)","(0.12285714285714286, 0.025864122802273418)","(0.29349625845928895, 0.01596240909109846)","(0.2829788128211044, 0.02623165522974578)","(0.625, 0.026645840148020798)","(0.028684298265066945, 0.005870482756271198)","(2.6368629899964824, 0.290311820080324)","(0.06802721088435375, 0.015569309803301476)","(0.0, 0.0)","(0.10030395136778116, 0.012093211290441238)","(0.46550976455345505, 0.14008290368012877)","(0.14904666091875957, 0.027706713503164327)","(0.7142857142857143, 0.04563404035713856)","(0.5, 0.050507627227610534)","(0.47959183673469385, 0.050465537530943905)","(0.2857142857142857, 0.04563404035713856)","(0.21428571428571427, 0.041449175533856936)","(0.02040816326530612, 0.0142827390249748)",98,"(0.0989719744077494, 0.029844915680858775)","(0.0904012904786707, 0.020020739385567227)","(0.1601961950546732, 0.020020739385567227)"
5,F3,"(-0.007270458679781041, 0.008724167539598949)","(0.3294915835428745, 0.019529140452026854)","(0.4732969835043, 0.02206647610060746)","(0.16946564885496182, 0.031017780268308877)","(0.2883024291440636, 0.01618459599060355)","(0.2728640687818084, 0.02473217999364995)","(0.5622317596566524, 0.020557409749246268)","(0.055351169591728804, 0.010926784560857822)","(3.248106324501248, 0.5417918133690408)","(0.0625, 0.017717084672307527)","(0.02380952380952382, 0.021735022123220874)","(0.13499344692005244, 0.011249157197355879)","(0.2602192554936134, 0.07528411588530234)","(0.14494986565986073, 0.03647205730030987)","(0.8791946308724832, 0.026698846456930426)","(0.7718120805369127, 0.03438024570094989)","(0.7315436241610739, 0.036304782729866154)","(0.12080536912751678, 0.026698846456930426)","(0.10738255033557047, 0.02536333799446498)","(0.040268456375838924, 0.016105130242060513)",149,"(0.1076191230668689, 0.029665438445522132)","(0.0832763670475306, 0.016021563366342067)","(0.20358331778380728, 0.016021563366342067)"
6,F4,"(0.009925078111774682, 0.012371186736148267)","(0.4670622679730822, 0.023464247753357113)","(0.608984177655782, 0.025157808378956266)","(0.1267080745341615, 0.02373848782650373)","(0.37478023327976195, 0.017295261321145866)","(0.33502240428198704, 0.02488629761646338)","(0.6216216216216216, 0.019842148733606308)","(0.03944403940523954, 0.010967586008851643)","(2.3860380842676028, 0.4870806452713538)","(0.08928571428571429, 0.012225949944311743)","(0.051020408163265314, 0.018294315448995818)","(0.09565217391304347, 0.010201736445573808)","(0.2992552427146773, 0.03544429418016482)","(0.09335314773568572, 0.020792815734513873)","(0.6736401673640168, 0.030329369907510364)","(0.5397489539748954, 0.03223994901323756)","(0.4811715481171548, 0.03231937184803326)","(0.3263598326359833, 0.030329369907510364)","(0.13389121338912133, 0.022027403659826306)","(0.058577405857740586, 0.015190022790896067)",239,"(0.1453958050452725, 0.049292670388930426)","(0.11104591982509263, 0.021539209039611023)","(0.2573079307382652, 0.021539209039611023)"
7,F11,"(0.001200574590731857, 0.018661956478739965)","(0.5029788968841977, 0.04137280954822298)","(0.4096916132045886, 0.032710053734874324)","(0.11898734177215191, 0.022944943706616518)","(0.30194661148830193, 0.020197157432516783)","(0.30194661148830193, 0.03180661254506039)","(0.626984126984127, 0.021711827183482517)","(0.041767652289119044, 0.006868247238793925)","(2.63460843833474, 0.3161782250550366)","(0.08755760368663593, 0.012497606396303675)","(nan, nan)","(0.08333333333333333, 0.010165625759880554)","(0.29015616854481374, 0.06649171983042082)","(0.13529796493490356, 0.03054496092097398)","(0.7247706422018348, 0.04277937409248436)","(0.44036697247706424, 0.04754948190694402)","(0.44036697247706424, 0.04754948190694402)","(0.27522935779816515, 0.04277937409248436)","(0.28440366972477066, 0.04321041141655161)","(0.0, 0.0)",109,"(0.17655867725873217, 0.04704276341033353)","(0.12041364347017637, 0.025244219271161134)","(0.18140474610450638, 0.025244219271161134)"
8,F9,"(0.017212901669503605, 0.013339421070814473)","(0.29960061422896694, 0.024260890330878745)","(0.45217925228226086, 0.02461602698272697)","(0.1183098591549296, 0.024159533812752675)","(0.21575600804185188, 0.015394841988721967)","(0.1983067450785891, 0.026014318117798047)","(0.6339285714285715, 0.02355839421248697)","(0.06116961152088725, 0.01505389824663925)","(3.7302401132775977, 0.8851631727994077)","(0.11278195488721805, 0.013361252881784039)","(0.07142857142857142, 0.03571428571428571)","(0.07440476190476189, 0.011127596366158012)","(nan, nan)","(0.2125523109800553, 0.07312134216176361)","(0.5966386554621849, 0.04497066927131235)","(0.4369747899159664, 0.0454693379827229)","(0.40336134453781514, 0.04497066927131235)","(0.40336134453781514, 0.04497066927131235)","(0.15966386554621848, 0.03357811857345877)","(0.03361344537815126, 0.016521842346441974)",119,"(0.15490216381549557, 0.05109962328626413)","(0.050607849167570516, 0.01111729772236796)","(0.07776654829698465, 0.01111729772236796)"
9,F10,"(-0.009691663072190581, 0.022217217225590252)","(0.4471255394057913, 0.039608276169116184)","(0.4523992191346507, 0.02683556011484567)","(0.12577319587628866, 0.022387761307836592)","(0.29563087558863693, 0.023743438174576095)","(0.24020727173944695, 0.025991798746492496)","(0.6298701298701299, 0.019829503896273647)","(0.05995714338596764, 0.005394037098827571)","(2.4876220023351703, 0.224769065276668)","(0.10714285714285714, 0.01093522206599633)","(0.04761904761904761, 0.01944039478399348)","(0.08894878706199462, 0.00951174334801895)","(nan, nan)","(0.15651525301796976, 0.005761306341187544)","(0.751937984496124, 0.038025618859851014)","(0.5038759689922481, 0.044021222583071264)","(0.4108527131782946, 0.043317178973290696)","(0.24806201550387597, 0.038025618859851014)","(0.24806201550387597, 0.038025618859851014)","(0.09302325581395349, 0.02557401929158873)",129,"(0.21314851619139932, 0.04651583477935168)","(0.10171641494985144, 0.02022380760471478)","(0.11629130823513391, 0.02022380760471478)"
10,M24_castre,"(0.00994332352043224, 0.030827806356592543)","(0.44870219545970186, 0.04109094756503429)","(0.412174334737272, 0.02985123286491805)","(0.12987012987012986, 0.023862802459202907)","(0.349416576248368, 0.028189125500916897)","(0.2650358091072458, 0.022955832775618513)","(0.611111111111111, 0.020472992533058017)","(0.059678802198082505, 0.0017008494109004382)","(1.8438180094228969, 0.0630162055053528)","(0.10924369747899158, 0.014697052641936239)","(0.08035714285714286, 0.017717084672307527)","(0.09090909090909093, 0.010360052405421627)","(nan, nan)","(0.12235723605885424, 0.011373221731298538)","(0.7064220183486238, 0.043619492143655944)","(0.5504587155963303, 0.047646819740456224)","(0.4036697247706422, 0.04699409274552115)","(0.29357798165137616, 0.043619492143655944)","(0.1559633027522936, 0.03475190588752658)","(0.14678899082568808, 0.03389703553897986)",109,"(0.20619067367887375, 0.042736897239860204)","(0.10570151362375742, 0.02170052578593042)","(0.14649140712979342, 0.02170052578593042)"
11,M25_castre,"(0.037918172207535884, 0.027626377839460245)","(0.40742013707122926, 0.03506442004359543)","(0.4830777283888195, 0.034574172026630136)","(0.12571428571428572, 0.025458016170234198)","(0.2959351836368821, 0.02028894421658752)","(0.2783177551374965, 0.023510834075924525)","(0.6194690265486725, 0.02363364900512844)","(0.03658247895597028, 0.012818933972785626)","(2.637349116914179, 0.5088854031034383)","(0.09022556390977443, 0.015809247610160806)","(0.14285714285714285, 0.06734350297014739)","(0.08630952380952382, 0.010926781136860466)","(nan, nan)","(0.15558063161696997, 0.028572970614952394)","(0.6481481481481481, 0.04595208114017962)","(0.4722222222222222, 0.048038217334177104)","(0.4444444444444444, 0.04781460921243724)","(0.35185185185185186, 0.04595208114017962)","(0.17592592592592593, 0.03663837222864994)","(0.027777777777777776, 0.015813195626480862)",108,"(0.11855803424378111, 0.049055616638029834)","(0.08643312863245664, 0.019018463615809538)","(0.15783184535331268, 0.019018463615809538)"
12,M26_castre,"(0.02984607032900404, 0.04231199621782445)","(0.46934643905621254, 0.0666292958311421)","(0.4193653854500556, 0.04608367322525737)","(0.12631578947368421, 0.02633968130001524)","(0.25400558721199135, 0.028054274437567594)","(0.23815596885226153, 0.03201478118191019)","(0.6263736263736264, 0.02549517631462832)","(0.08935573490914396, 0.050869310161491245)","(1.7466013056830212, 1.9056823304508168)","(0.1142857142857143, 0.011428571428571429)","(0.14285714285714285, 0.10101525445522108)","(0.06666666666666665, 0.013012000972647111)","(nan, nan)","(0.21058312472184082, 0.04210158871798052)","(0.5229357798165137, 0.04784090127601062)","(0.29357798165137616, 0.043619492143655944)","(0.27522935779816515, 0.04277937409248436)","(0.47706422018348627, 0.04784090127601062)","(0.22935779816513763, 0.04026891242792926)","(0.01834862385321101, 0.012854853742188893)",109,"(0.33201546824512285, 0.20673814146447766)","(0.11172235588244381, 0.028183012165086552)","(0.11488846658669916, 0.028183012165086552)"
13,castre,"(0.025685546312769897, 0.017520409003798088)","(0.43905567348463304, 0.02584862975157787)","(0.4433317288343865, 0.021115515261815522)","(0.12745098039215685, 0.019893015007056078)","(0.3056992713956508, 0.014886690959823)","(0.2633977429333765, 0.014903107031924)","(0.6181818181818182, 0.013269432285435524)","(0.05601164475026131, 0.016391790705998468)","(2.1710223705692524, 0.6227472114161636)","(0.10538641686182669, 0.008045878233918518)","(0.09523809523809525, 0.020026668631128904)","(0.08313817330210774, 0.0065907822453087584)","(nan, nan)","(0.15415355112439658, 0.02457281604192325)","(0.6257668711656442, 0.02680208615845811)","(0.4386503067484663, 0.02748319146872453)","(0.37423312883435583, 0.02680208615845811)","(0.37423312883435583, 0.02680208615845811)","(0.18711656441717792, 0.02160038312954705)","(0.06441717791411043, 0.013596689093518485)",326,"(0.1929544232075704, 0.06499786801703945)","(0.09975691594916636, 0.016641225560768993)","(0.1418849548864923, 0.016641225560768993)"
14,M,"(0.0003352374671111531, 0.010337624336493184)","(0.5763462182617156, 0.028584149427291657)","(0.4154791035212741, 0.01663290911441982)","(0.1326388888888889, 0.019564986382607185)","(0.39474350337864345, 0.017769320618635225)","(0.3100411572153454, 0.021321439136667057)","(0.6114649681528662, 0.011949244378274205)","(0.029836645039541553, 0.007196518867686334)","(2.6990823406937197, 0.37002055019548163)","(0.09195402298850576, 0.007334963236779836)","(0.10064935064935066, 0.009825970780234538)","(0.09463148316651503, 0.006631067164001836)","(0.4510839687072573, 0.06989112457851986)","(0.11532147406631138, 0.007378602343885214)","(0.75, 0.02209708691207961)","(0.5234375, 0.025487470553039532)","(0.4088541666666667, 0.02508799290881269)","(0.25, 0.02209708691207961)","(0.2265625, 0.021361955912331403)","(0.11458333333333333, 0.01625432579086285)",384,"(0.12964702643552883, 0.03721429203387057)","(0.18044432813011477, 0.028080771187507986)","(0.2164864451690101, 0.028080771187507986)"
15,F,"(0.0033138582431372675, 0.006223258122597629)","(0.40071745202081155, 0.012313741230691871)","(0.5062130985816408, 0.011813798614463055)","(0.1346938775510204, 0.019103241030728427)","(0.30174597502985884, 0.008455526147727642)","(0.2747760326403595, 0.01292871066741844)","(0.6097285067873304, 0.00985564101009087)","(0.051395910105908604, 0.004364277927680511)","(2.8162193608894377, 0.2095985147140114)","(0.0934065934065934, 0.005960773934172361)","(0.04761904761904761, 0.01122391716169123)","(0.10187667560321716, 0.005255629971328681)","(0.3606584869383567, 0.02926403753679639)","(0.14035477514587333, 0.02879336096348602)","(0.723489932885906, 0.016386778509855992)","(0.548993288590604, 0.018230428787863608)","(0.5006711409395973, 0.018318566133691115)","(0.276510067114094, 0.016386778509855992)","(0.174496644295302, 0.013905122682380578)","(0.04832214765100671, 0.007856696173431432)",745,"(0.15290404075069522, 0.025708689145394984)","(0.09006467416254957, 0.013069997999735277)","(0.1643282006275855, 0.013069997999735277)"
16,Ovx,"(0.004069888665835643, 0.020847640523899477)","(0.5551782682512734, 0.044352057288068916)","(0.5942275042444821, 0.03255042690493521)","(0.18318318318318316, 0.025050556666427432)","(0.400679117147708, 0.028901441660560544)","(0.3195876288659794, 0.021100449489011436)","(0.5751295336787565, 0.009846869477673785)","(0.06621370499419292, inf)","(2.072682926829266, inf)","(0.12244897959183675, 0.005240332561358119)","(0.1372549019607843, 0.013114978942297751)","(0.1331338818249813, 0.007178508235018961)","(0.4655061577669936, 0.07004145281222669)","(0.12305003315737885, 0.0138583121312139)","(0.7585421412300684, 0.0204257620846428)","(0.55125284738041, 0.023737993998616664)","(0.43507972665148065, 0.02366168909859411)","(0.24145785876993167, 0.0204257620846428)","(0.2072892938496583, 0.01934699581754069)","(0.11617312072892938, 0.015293404324388594)",439,"(0.20067568121914503, inf)","(0.22862939275153013, 0.036209461735646355)","(0.32449592449592457, 0.036209461735646355)"
17,Notch1_F,"(0.20027921430201143, 0.28561383466633333)","(0.532520325203252, 0.06714272385120863)","(0.5853658536585364, 0.052409355346453475)","(0.04885496183206106, 0.012393347071971773)","(0.32510288065843623, 0.03472143197043463)","(0.2647058823529412, 0.02530024829583031)","(0.8086419753086419, 0.02428211243157265)","(0.17708333333333331, inf)","(0.1250000000000008, inf)","(0.04120879120879122, 0.008975185556036321)","(0.026785714285714284, 0.013939727674996424)","(0.03174603174603176, 0.00748261144112749)","(0.6949958147984131, 0.08215995745584538)","(0.21257466791677104, 0.0037969264292400597)","(0.2514395393474088, 0.01900690335242209)","(0.15163147792706333, 0.015713325080450393)","(0.12092130518234165, 0.014283887754951286)","(0.7485604606525912, 0.01900690335242209)","(0.09980806142034548, 0.01313201917570963)","(0.030710172744721688, 0.007558734576419405)",521,"(1.9302128324017613, inf)","(0.05565217391304346, 0.015765294933965134)","(0.054961832061068694, 0.015765294933965134)"
18,Notch1_M,"(-0.3319512744041543, 0.17130268663716167)","(0.8698630136986302, 0.1280834457924373)","(0.4520547945205479, 0.06838588446982308)","(0.06000000000000001, 0.01432761144783037)","(0.4068965517241379, 0.04633551917672357)","(0.33599999999999997, 0.040799953852783385)","(0.783132530120482, 0.024069699994952194)","(-0.0025510204081633054, inf)","(3.0952380952380993, inf)","(0.04761904761904761, 0.008107205054845221)","(0.016806722689075633, 0.011163212842942376)","(0.04545454545454545, 0.011032013926228306)","(2.5, 150977.1690478932)","(0.15222482207645022, 0.043568918892182604)","(0.26804123711340205, 0.020112832869112793)","(0.12577319587628866, 0.015056888622843984)","(0.09072164948453608, 0.01304166454173929)","(0.7319587628865979, 0.020112832869112796)","(0.1422680412371134, 0.015862024004681417)","(0.03505154639175258, 0.0083509287695453)",485,"(-0.036983971670860705, -inf)","(0.40105263157894755, 0.11251195105007325)","(0.12292682926829267, 0.11251195105007325)"

In [ ]:
mdata[['Mouse', 'nclones', '#S4+', '#T3', '#T', '#D'] ]

,Mouse,nclones,#S4+,#T3,#T,#D
0,M30,57,"(0.3508771929824561, 0.06321258874556504)","(0.17543859649122806, 0.0503775039171214)","(0.3157894736842105, 0.06156817388058966)","(0.15789473684210525, 0.04829804923590773)"
1,M1,67,"(0.34328358208955223, 0.058006685713137024)","(0.1791044776119403, 0.04684462467949339)","(0.208955223880597, 0.049669495472589524)","(0.26865671641791045, 0.05415294608121959)"
2,M14,86,"(0.32558139534883723, 0.05052953894914609)","(0.18604651162790697, 0.04196249808820081)","(0.19767441860465115, 0.042943884806284104)","(0.29069767441860467, 0.04896516755606225)"
3,M3,76,"(0.5131578947368421, 0.057334070632943414)","(0.05263157894736842, 0.025613908599594084)","(0.2236842105263158, 0.04780024010173328)","(0.21052631578947367, 0.046764385086244135)"
4,M1bis,98,"(0.47959183673469385, 0.050465537530943905)","(0.02040816326530612, 0.0142827390249748)","(0.21428571428571427, 0.041449175533856936)","(0.2857142857142857, 0.04563404035713856)"
5,F3,149,"(0.7315436241610739, 0.036304782729866154)","(0.040268456375838924, 0.016105130242060513)","(0.10738255033557047, 0.02536333799446498)","(0.12080536912751678, 0.026698846456930426)"
6,F4,239,"(0.4811715481171548, 0.03231937184803326)","(0.058577405857740586, 0.015190022790896067)","(0.13389121338912133, 0.022027403659826306)","(0.3263598326359833, 0.030329369907510364)"
7,F11,109,"(0.44036697247706424, 0.04754948190694402)","(0.0, 0.0)","(0.28440366972477066, 0.04321041141655161)","(0.27522935779816515, 0.04277937409248436)"
8,F9,119,"(0.40336134453781514, 0.04497066927131235)","(0.03361344537815126, 0.016521842346441974)","(0.15966386554621848, 0.03357811857345877)","(0.40336134453781514, 0.04497066927131235)"
9,F10,129,"(0.4108527131782946, 0.043317178973290696)","(0.09302325581395349, 0.02557401929158873)","(0.24806201550387597, 0.038025618859851014)","(0.24806201550387597, 0.038025618859851014)"
10,M24_castre,109,"(0.4036697247706422, 0.04699409274552115)","(0.14678899082568808, 0.03389703553897986)","(0.1559633027522936, 0.03475190588752658)","(0.29357798165137616, 0.043619492143655944)"
11,M25_castre,108,"(0.4444444444444444, 0.04781460921243724)","(0.027777777777777776, 0.015813195626480862)","(0.17592592592592593, 0.03663837222864994)","(0.35185185185185186, 0.04595208114017962)"
12,M26_castre,109,"(0.27522935779816515, 0.04277937409248436)","(0.01834862385321101, 0.012854853742188893)","(0.22935779816513763, 0.04026891242792926)","(0.47706422018348627, 0.04784090127601062)"
13,castre,326,"(0.37423312883435583, 0.02680208615845811)","(0.06441717791411043, 0.013596689093518485)","(0.18711656441717792, 0.02160038312954705)","(0.37423312883435583, 0.02680208615845811)"
14,M,384,"(0.4088541666666667, 0.02508799290881269)","(0.11458333333333333, 0.01625432579086285)","(0.2265625, 0.021361955912331403)","(0.25, 0.02209708691207961)"
15,F,745,"(0.5006711409395973, 0.018318566133691115)","(0.04832214765100671, 0.007856696173431432)","(0.174496644295302, 0.013905122682380578)","(0.276510067114094, 0.016386778509855992)"
16,ovx,439,"(0.43507972665148065, 0.02366168909859411)","(0.11617312072892938, 0.015293404324388594)","(0.2072892938496583, 0.01934699581754069)","(0.24145785876993167, 0.0204257620846428)"
17,Notch1_F,521,"(0.12092130518234165, 0.014283887754951286)","(0.030710172744721688, 0.007558734576419405)","(0.09980806142034548, 0.01313201917570963)","(0.7485604606525912, 0.01900690335242209)"
18,Notch1_M,485,"(0.09072164948453608, 0.01304166454173929)","(0.03505154639175258, 0.0083509287695453)","(0.1422680412371134, 0.015862024004681417)","(0.7319587628865979, 0.020112832869112796)"
19,Lgr6_F,110,"(0.5181818181818182, 0.04764159961130258)","(0.07272727272727272, 0.02476030851051108)","(0.15454545454545454, 0.03446489083437512)","(0.2545454545454545, 0.04153334543315795)"
20,Lgr6_M,149,"(0.5033557046979866, 0.04096067349864932)","(0.1476510067114094, 0.029062555411336854)","(0.24161073825503357, 0.03506800578347937)","(0.10738255033557047, 0.02536333799446498)"